---
title: "HLA-DPB1 mismatch scores Tutorial"
author: "Lars van der Burg & Joost van der Hem"
date: "2024-06-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(ggVennDiagram)


source("Functions/DP_setup.R")
source("Functions/score_table.R")
source("Functions/Venn_diagram.R")


load("Data/Example_Data.RData")
load("Data/Peptide_data_count.Rdata")
load("Data/Peptide_data_ratio.Rdata")
load("Data/Venn_Data.Rdata")
```


## Calculate mismatch scores
```{r}
DPB1_genes = c("HLA_DPP1", "HLA_DPP2", "HLA_DPD1", "HLA_DPD2")
MMS_count = DP_setup(Data = Data, DPB1_genes = DPB1_genes, peptide_data = peptide_data_count)
MMS_ratio = DP_setup(Data = Data, DPB1_genes = DPB1_genes, peptide_data = peptide_data_ratio)


discard_index = MMS_count$discard_index
if(length(discard_index) != 0){
  Data = Data[-discard_index, ]
  
  MMS_count = MMS_count$mismatch_score[-discard_index]
  MMS_ratio = MMS_ratio$mismatch_score[-discard_index]
}


long_count = peptide_data_count |> 
  dplyr::mutate(Donor = rownames(peptide_data_count)) |> 
  tidyr::pivot_longer(-Donor) |> 
  dplyr::rename(Patient = name, Count = value)

long_ratio = peptide_data_ratio |> 
  dplyr::mutate(Donor = rownames(peptide_data_ratio)) |> 
  tidyr::pivot_longer(-Donor) |> 
  dplyr::rename(Patient = name, Ratio = value)

mismatches = long_count |> 
  dplyr::full_join(long_ratio, by = c("Donor", "Patient")) |> 
  dplyr::relocate(Patient) |> 
  dplyr::mutate(Count = as.integer(Count))
```


## Venn diagram
```{r}
Pat1 = "03:01"; Pat2 = "04:01"
Don1 = "01:01"; Don2 = "02:01"


score_table(mismatches = mismatches, Pat1 = Pat1, Pat2 = Pat2, Don1 = Don1, Don2 = Don2)
venn_diagram(Venn_Data = Venn_Data, Pat1 = Pat1, Pat2 = Pat2, Don1 = Don1, Don2 = Don2)
```







